# ==================== LOAD BALANCERS ====================
[lb]
tkngdp-prig-np-lb-01 ansible_host=10.248.124.194
tkngdp-prig-np-lb-02 ansible_host=10.248.124.195

[lb:vars]
ansible_user=*******
ansible_pass=**************

# ==================== APPLICATION SERVERS ====================
[app]
tkngdp-prig-np-app-01 ansible_host=10.248.124.196
tkngdp-prig-np-app-02 ansible_host=10.248.124.197

[app:vars]
ansible_user=*******
ansible_pass=**************

# ==================== CONFIGURATION SERVERS ====================
[cfg]
tkngdp-prig-np-cfg-01 ansible_host=10.248.124.200
tkngdp-prig-np-cfg-02 ansible_host=10.248.124.201

[cfg:vars]
ansible_user=*******
ansible_pass=**************

# ==================== WEB SERVERS ====================
[web]
tkngdp-prig-np-web-01 ansible_host=10.248.124.198
tkngdp-prig-np-web-02 ansible_host=10.248.124.199

[web:vars]
ansible_user=*******
ansible_pass=**************

# ==================== DATABASE SERVERS ====================
[db]
tkngdp-prig-np-db-01 ansible_host=10.248.124.131
tkngdp-prig-np-db-02 ansible_host=10.248.124.132

[db:vars]
ansible_user=*******
ansible_pass=**************

# ==================== GROUP DEFINITIONS ====================
# Группы по типам экспортеров
[node_exporter:children]
lb
app
cfg
web
db

[docker_exporter:children]
lb
app
cfg
web
db

[blackbox_exporter:children]
lb

[x509_exporter:children]
lb

[postgres_exporter:children]
db